
<!doctype html><html lang=en><head><meta name=generator content="Hugo 0.65.3"><script async src="https://www.googletagmanager.com/gtag/js?id=UA-163317841-1"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
    gtag('js',new Date());gtag('config','UA-163317841-1');</script><link rel=stylesheet href=/scss/codecss.css><meta name=viewport content="width=device-width,initial-scale=1"><title itemprop=name>Home</title><meta property="og:title" content="Home | Davis Haupt"><meta name=twitter:title content="Home | Davis Haupt"><meta itemprop=name content="Home | Davis Haupt"><meta name=application-name content="Home | Davis Haupt"><meta property="og:site_name" content="Davis Haupt"><meta name=description content="Hi there! I&rsquo;m Davis, a Senior at the University of Pennsylvania studying Computer Science. I&rsquo;m really passionate about software engineering, spaceflight and elections.
    I spend a lot of my time building open source products for Penn students at Penn Labs. Starting in the fall, I&rsquo;ll be working at MongoDB as a Software Engineer."><meta itemprop=description content="Hi there! I&rsquo;m Davis, a Senior at the University of Pennsylvania studying Computer Science. I&rsquo;m really passionate about software engineering, spaceflight and elections.
    I spend a lot of my time building open source products for Penn students at Penn Labs. Starting in the fall, I&rsquo;ll be working at MongoDB as a Software Engineer."><meta property="og:description" content="Hi there! I&rsquo;m Davis, a Senior at the University of Pennsylvania studying Computer Science. I&rsquo;m really passionate about software engineering, spaceflight and elections.
    I spend a lot of my time building open source products for Penn students at Penn Labs. Starting in the fall, I&rsquo;ll be working at MongoDB as a Software Engineer."><meta name=twitter:description content="Hi there! I&rsquo;m Davis, a Senior at the University of Pennsylvania studying Computer Science. I&rsquo;m really passionate about software engineering, spaceflight and elections.
    I spend a lot of my time building open source products for Penn students at Penn Labs. Starting in the fall, I&rsquo;ll be working at MongoDB as a Software Engineer."><base href=/><link rel=canonical href=/ itemprop=url><meta name=url content="/"><meta name=twitter:url content="/"><meta property="og:url" content="/"><meta itemprop=image content="/"><meta property="og:image" content="/"><meta name=twitter:image content="/"><meta name=twitter:image:src content="/"><link href=/index.xml rel=alternate type=application/rss+xml title="Davis Haupt"><link href=/index.xml rel=feed type=application/rss+xml title="Davis Haupt"></head><body><nav class=navbar><a href=/ aria-label=home><ul class=prompt aria-hidden=true><span class=prompt-mark>></span>
    <span class=prompt-text>~/</span>
    <span class=prompt-cursor></span></ul></a><ul class=links><li><a href=..>Sites feitos</a></li></ul></nav><div id=content><section class=hero><h1>Oliveira</h1><h4>Tentando fazer algo diferente no tempo livre</h4><div class=links><a href=https://github.com/davish/><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37.0 00-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44.0 0020 4.77 5.07 5.07.0 0019.91 1S18.73.65 16 2.48a13.38 13.38.0 00-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07.0 005 4.77a5.44 5.44.0 00-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37.0 009 18.13V22" /></svg></a><a href=https://linkedin.com/in/davishaupt/><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin"><path d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6z" /><rect x="2" y="9" width="4" height="12" /><circle cx="4" cy="4" r="2" /></svg></a><a href=/blog/index.xml><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-rss"><path d="M4 11a9 9 0 019 9"/><path d="M4 4a16 16 0 0116 16"/><circle cx="5" cy="19" r="1"/></svg></a></div><hr></section><section id=bio><p><strong>Oi Gente</strong> Eu sou Oliver e estou tentando fazer algo de diferente</strong>></section></div><footer></footer>
    </body>
    </html>